

export const tempArticles = [
        {
                id: 112,
                title: "some tda fraaaaaaaa efsae itle adjaouhda adgaywg dautwfg autaew a67ghdw",
                body: "небольшое и не очень точное описание",
                slug: "some-title",
                likes: [9, 6, 28],
                author: "dakowrn89",
                imgSrc: "",
                publish: true,
                post_preview: "some descr  fraaaaaaaa efsae itle adjaouhda adgaywg dautwfg autaew a67ghdw iption ",
              },
              {
                id: 112,
                title: "some tda fraaaaaaaa efsae itle adjaouhda adgaywg dautwfg autaew a67ghdw",
                body: "небольшое и не очень точное описание",
                slug: "some-title",
                likes: [9, 6, 28],
                author: "dakowrn89",
                imgSrc: "",
                publish: true,
                post_preview: "some description  fraaaaaaaa efsae itle adjaouhda adgaywg dautwfg autaew a67ghdw",
              },
  {
    id: 101,
    title: "some title  fraaaaaaaa efsae itle adjaouhda adgaywg dautwfg autaew a67ghdw",
    body: "небольшое и не очень точное описание",
    slug: "some-title",
    likes: [9, 6, 28],
    author: "dakowrn89",
    imgSrc: "",
    publish: true,
    post_preview: `ajdio9qwy diqaywg780 xdaikgwi bhdaiwabY GUIyW GWYgaw id W fraaaaaaaa efsae itle adjaouhda adgaywg dautwfg autaew a67ghdwIu`
  },
  {
    id: 102,
    title: "some title",
    body: "небольшое и не очень точное описание",
    slug: "some-title",
    likes: [9, 6, 28],
    author: "dakowrn89",
    imgSrc: "",
    publish: true,
    post_preview: "some description",
  },
  {
    id: 103,
    title: "some title",
    body: "небольшое и не очень точное описание",
    slug: "some-title",
    likes: [9, 6, 28],
    author: "dakowrn89",
    imgSrc: "",
    publish: true,
    post_preview: "some description",
  },
  {
    id: 104,
    title: "some title",
    body: "небольшое и не очень точное описание",
    slug: "some-title",
    likes: [9, 6, 28],
    author: "dakowrn89",
    imgSrc: "",
    publish: true,
    post_preview: "some description",
  },
  {
    id: 105,
    title: "some title",
    body: "небольшое и не очень точное описание",
    slug: "some-title",
    likes: [9, 6, 28],
    author: "dakowrn89",
    imgSrc: "",
    publish: true,
    post_preview: "some description",
  },
  {
    id: 106,
    title: "some title",
    body: "небольшое и не очень точное описание",
    slug: "some-title",
    likes: [9, 6, 28],
    author: "dakowrn89",
    imgSrc: "",
    publish: true,
    post_preview: "some description",
  },
  {
    id: 107,
    title: "some title",
    body: "небольшое и не очень точное описание",
    slug: "some-title",
    likes: [9, 6, 28],
    author: "dakowrn89",
    imgSrc: "",
    publish: true,
    post_preview: "some description",
  },
  {
    id: 108,
    title: "some title",
    body: "небольшое и не очень точное описание",
    slug: "some-title",
    likes: [9, 6, 28],
    author: "dakowrn89",
    imgSrc: "",
    publish: true,
    post_preview: "some description",
  },
  {
    id: 109,
    title: "some title",
    body: "небольшое и не очень точное описание",
    slug: "some-title",
    likes: [9, 6, 28],
    author: "dakowrn89",
    imgSrc: "",
    publish: true,
    post_preview: "some description",
  },
  {
    id: 110,
    title: "some title",
    body: "небольшое и не очень точное описание",
    slug: "some-title",
    likes: [9, 6, 28],
    author: "dakowrn89",
    imgSrc: "",
    publish: true,
    post_preview: `ajdio9qwy diqaywg780 xdaikgwi bhdaiwabY GUIyW GWYgaw id WIu`
  },
  {
    id: 111,
    title: "some title",
    body: "небольшое и не очень точное описание",
    slug: "some-title",
    likes: [9, 6, 28],
    author: "dakowrn89",
    imgSrc: "",
    publish: true,
    post_preview: "some description",
  },
  {
    id: 112,
    title: "some tda fraaaaaaaa efsae itle adjaouhda adgaywg dautwfg autaew a67ghdw",
    body: "небольшое и не очень точное описание",
    slug: "some-title",
    likes: [9, 6, 28],
    author: "dakowrn89",
    imgSrc: "",
    publish: true,
    post_preview: "someda  dja8uwyhd fvhw7egual dyqaw6fg wg67wh a87w description",
  },
  {
    id: 113,
    title: "some tidwe tgfrfgsp8f ahg aga ajwiu w787 tle",
    body: "небольшое и не очень точное описание",
    slug: "some-title",
    likes: [9, 6, 28],
    author: "dakowrn89",
    imgSrc: "",
    publish: true,
    post_preview: `ajdio9qwy diqaywg780 xdaikgwi bhdaiwabY GUIyW GWYgaw id WIu`
  },
  {
    id: 114,
    title: "some titsdsadg greddddd  ew dddddddddaw erfewr esale",
    body: "небольшое и не очень точное описание",
    slug: "some-title",
    likes: [9, 6, 28],
    author: "dakowrn89",
    imgSrc: "",
    publish: true,
    post_preview: `ajdio9qwy diqaywg780 xdaikgwi wadwabdaaadw wdaiwabY GUIyW GWYgaw id WIu`
  },
  {
    id: 115,
    title: "some title",
    body: "небольшое и не очень точное описание",
    slug: "some-title",
    likes: [9, 6, 28],
    author: "dakowrn89",
    imgSrc: "",
    publish: true,
    post_preview: `ajdio9qwy diqaywg780 xdaikgwi bhdaiwabY GUIyW GWYgaw id WIu`
  },
];
