# Generated by Django 4.2.7 on 2023-11-30 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0004_alter_post_options_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='craft_offered',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='experience',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=200, null=True, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL профиля'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин пользователя'),
        ),
    ]
